### ISSUE TITLE
Getting started guide?

### ISSUE THREAD

**Issue by mattdsteele** [jjh456/GeekwayGameLibrary#1]
First of all @jjh456, thanks for sharing this. I've been coming to Geekway since 2009 and it's gotten better every year. No small part of it has been the ease of checkin/checkout with the digital system. 🎉 

Anyhow, I've been [running a board game library](https://steele.blue/conference-board-games/) at a JavaScript conf, but we've been using pen & paper for our system. I'd love to change that!

I'm not a C# developer; so any info on how to get started would be great. Chiefly:

* What do I need installed? Do I need a particular Visual Studio, or just a runtime?
* Do I need a database running somewhere?
* How to populate the game library, and/or users?
* What are the steps to build & run the solution?
* What kind of hardware? Any specific barcode scanner?
* Does this just run on one machine or can I have multiple PCs act as clients?

Not trying to impose a ton of extra work on you, but I'm pretty excited to try this out. Cheers!

p.s. I'll be at Geekway, hope to see you there!

**Comment by commadelimited** [comment]
Subscribing.

**Comment by jjh456** [comment]
@mattdsteele I appreciate the kind words and hopefully I can help get you up and running!

- What do I need installed? Do I need a particular Visual Studio, or just a runtime?
**Right now I believe you'd want Visual Studio to build the code base, but I could probably pretty easily put together a compiled version for you to host.**
- Do I need a database running somewhere?
**Yes.  The database is SQL server.  I use SQL Server express (it's free)**
- How to populate the game library, and/or users?
**You have two options:  manually within the system adding each one, or there's a CSV import feature as well.**
**The format for the attendee CSV is simply: Name, BadgeID (needs to be unique).**
**The other import creates Games and Copies (each Copy is of a particular Game) in the system.  The format for this CSV import is: GameTitle, LibraryID (needs to be unique), OwnerName.  So if you have two copies in that list with the same GameTitle, it will create one Game entity and two Copy entities during the import.**
- What are the steps to build & run the solution?
**For building and running you'd definitely want to download Visual Studio Community edition (again, free).**
- What kind of hardware? Any specific barcode scanner?
**PCs running Windows will mostly all be fine I think.  I am honestly not 100% sure on the hardware requirements to run IIS and SQL server, but I can't imagine they're too crazy.  I think any barcode scanner will work, but we have been using https://www.amazon.com/gp/product/B006LVO56W**
**Oh, it is important to write any barcodes in a font that's read by the barcode scanner you're using.  We use the Code 39 font https://www.barcodesinc.com/free-barcode-font/**
- Does this just run on one machine or can I have multiple PCs act as clients?
**You set it up on one PC per library at this point in time.  Then you can from that PC serve up the web app for any other PC on the same network to access.  I've been hosting it via IIS.**

 A few other things:
- Check the top answer here for how to set up IIS on your host machine: http://stackoverflow.com/questions/9794985/iis-this-configuration-section-cannot-be-used-at-this-path-configuration-lock
- IIS applications are typically deployed at: c\inetpub\wwwroot\YourSiteNameHere\
- .NET apps have a file called Web.config.  This file will have a connection string for connecting to the database.  You'll have to update that for your instance.  https://www.connectionstrings.com/sql-server/

Hopefully this is helpful to get you started!  It's been about a year since I set this up, so I'm certain I've missed important points.  I'll consider this a decent starting place for a full guide though.  Feel free to let me know if/when you come up with any snags.

If I end up seeing you at Geekway, maybe we can play a game! 🎲

**Comment by mattdsteele** [comment]
Awesome. I'll start giving this a go and will let you know if I've got any other questions. First task is to acquire a Windows machine...

Thanks!
